service:
  golangci-lint-version: 1.16.0
run:
  deadline: 5m
  issues-exit-code: 1
  skip-files:
    - ".*_mock_test.go"

linters-settings:
  lll:
    line-length: 200
  misspell:
    locale: US
  gocyclo:
    min-complexity: 20

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - gocognit
        - errcheck
        - dupl
        - gosec
        - funlen
    - linters:
        - stylecheck
      source: "package (cert_manager|domain_checker)"

linters:
  enable-all: true
  disable:
    - gochecknoglobals

