service:
  golangci-lint-version: 1.16.0
run:
  deadline: 5m
  issues-exit-code: 1

linters-settings:
  lll:
    line-length: 200
  misspell:
    locale: US
  gocyclo:
    min-complexity: 20

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

linters:
  enable-all: true
  disable:
    - gochecknoglobals

