service:
  golangci-lint-version: 1.16.0
run:
  deadline: 5m
  issues-exit-code: 1

linters-settings:
  lll:
    line-length: 200
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - gochecknoglobals
